title: Aerlavynah
description: "Dreamy's Dreams"
baseurl: ""
url: "https://aerlavynah.com"

theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-paginate

paginate: 5
paginate_path: "/page:num/"

exclude:
  - Gemfile
  - Gemfile.lock        
  - node_modules
  - vendor
  - .jekyll-cache
  - .sass-cache
  - .DS_Store
  - .gitignore
  - .git

markdown: kramdown

collections:
  poems:
    output: true
    permalink: /poems/:name/

include:
  - poems-data.js

defaults:
  -
    scope:
      path: ""
    values:
      sitemap: true
