title: Aerlavynah
description: "Dreamy's Dreams"
baseurl: ""
url: "https://ratanahaerlavynah.github.io"

theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap

markdown: kramdown
collections:
  poems:
    output: true
    permalink: /poems/:name/
    
    
