title: Aerlavynah
description: "Dreamy's Dreams"
baseurl: ""                  # racine du domaine
url: "https://aerlavynah.com"

theme: minima

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-paginate
  - jekyll-compress-html

paginate: 5
paginate_path: "/page:num/"

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .jekyll-cache
  - .sass-cache
  - .DS_Store
  - .gitignore
  - .git

markdown: kramdown

collections:
  poems:
    output: true
    permalink: /poems/:name/

include:
  - poems-data.js            # un seul fichier mais on garde le tiret, YAML adore
  - manifest.webmanifest
  - offline.html
webrick:
  mime_types:
    .webmanifest: application/manifest+json

defaults:
  - scope:
      path: ""               # s’applique à tout le site
    values:
      sitemap: true



